[tool.poetry]
name = "rimoto_plex_companion"
version = "0.1.0"
description = "Rclone Mount Compatible, media scanner - sonarr or radarr straight to plex."
authors = ["Kieran <3812864+MDCEY@users.noreply.github.com>"]
license = "MIT"
include = ["userscripts/*"]

[tool.poetry.dependencies]
python = "^3.7"
logzero = "^1.5"
hug = "^2.4"
tinydb = "^3.13"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0",allows-prereleases = true}
pylint = "^2.3"

[tool.poetry.scripts]
Rimoto='Rimoto_plex_companion.app:main'
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

